/*
 * DO NOT EDIT THIS FILE, it is auto-generated. It will be updated automatically.
 * All changes done to this file will be lost upon re-running the 'silence createapi' command.
 * If you want to create new API methods, define them in a new file.
 *
 * Silence is built and maintained by the DEAL research group at the University of Seville.
 * You can find us at https://deal.us.es
 */

"use strict";

import { BASE_URL, requestOptions } from './common.js';

const authAPI_auto = {

    /** Logs in using an identifier and password */
    login: async function(formData) {
        let response = await axios.post(`${BASE_URL}/login`, formData, requestOptions);
        return response.data;
    },

    /** Registers a new user and stores the password safely in the database */
    register: async function(formData) {
        let response = await axios.post(`${BASE_URL}/register`, formData, requestOptions);
        return response.data;
    },
};

export { authAPI_auto };