/*
 * DO NOT EDIT THIS FILE, it is auto-generated. It will be updated automatically.
 * All changes done to this file will be lost upon re-running the 'silence createapi' command.
 * If you want to create new API methods, define them in a new file.
 *
 * Silence is built and maintained by the DEAL research group at the University of Seville.
 * You can find us at https://deal.us.es
 */

"use strict";

import { BASE_URL, requestOptions } from './common.js';

const relaciones_y_citasAPI_auto = {

    /** Gets all entries from 'relaciones_y_citas' */
    getAll: async function() {
        let response = await axios.get(`${BASE_URL}/relaciones_y_citas`, requestOptions);
        return response.data;
    },

    /** Gets an entry from 'relaciones_y_citas' by its primary key */
    getById: async function(relacionCitaId) {
        let response = await axios.get(`${BASE_URL}/relaciones_y_citas/${relacionCitaId}`, requestOptions);
        return response.data[0];
    },

    /** Creates a new entry in 'relaciones_y_citas' */
    create: async function(formData) {
        let response = await axios.post(`${BASE_URL}/relaciones_y_citas`, formData, requestOptions);
        return response.data;
    },

    /** Updates an existing entry in 'relaciones_y_citas' by its primary key */
    update: async function(formData, relacionCitaId) {
        let response = await axios.put(`${BASE_URL}/relaciones_y_citas/${relacionCitaId}`, formData, requestOptions);
        return response.data;
    },

    /** Deletes an existing entry in 'relaciones_y_citas' by its primary key */
    delete: async function(relacionCitaId) {
        let response = await axios.delete(`${BASE_URL}/relaciones_y_citas/${relacionCitaId}`, requestOptions);
        return response.data;
    },
};

export { relaciones_y_citasAPI_auto };